CREATE TABLE `category` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `code` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'code',
  `p_code` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '父节点',
  `name` varchar(100) NOT NULL DEFAULT '' COMMENT 'category name',
  `p_name` varchar(100) NOT NULL DEFAULT '' COMMENT 'category parent name',
  `url` varchar(500) NOT NULL DEFAULT '' COMMENT 'url',
  PRIMARY KEY (`id`),
  KEY `idx_name` (`name`),
  KEY `idx_p_name` (`p_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='分类';

INSERT INTO `category` (`id`, `code`, `p_code`, `name`, `p_name`, `url`)
VALUES
	(1, 0, 1, 'After sun product', 'Sun', '/skindeep/browse/after+sun+product/'),
	(2, 0, 1, 'Sunless tanning', 'Sun', '/skindeep/browse/sunless+tanning/'),
	(3, 0, 1, 'Sunscreen: lip balm', 'Sun', '/skindeep/browse/sunscreen:+lip+balm/'),
	(4, 0, 1, 'Sunscreen: makeup', 'Sun', '/skindeep/browse/sunscreen:+makeup/'),
	(5, 0, 1, 'Sunscreen: moisturizer', 'Sun', '/skindeep/browse/sunscreen:+moisturizer/'),
	(6, 0, 1, 'Sunscreen: SPF less than 15', 'Sun', '/skindeep/browse/sunscreen:+SPF+less+than+15/'),
	(7, 0, 1, 'Sunscreen: SPF 15-30', 'Sun', '/skindeep/browse/sunscreen:+SPF+15-30/'),
	(8, 0, 1, 'Sunscreen: SPF greater than 30', 'Sun', '/skindeep/browse/sunscreen:+SPF+greater+than+30/'),
	(9, 0, 1, 'Tanning oil', 'Sun', '/skindeep/browse/tanning+oil/'),
	(10, 1, 0, 'Sun', '', ''),
	(12, 2, 0, 'Makeup', '', ''),
	(13, 204, 2, 'Other', 'Makeup', ''),
	(14, 201, 2, 'Face', 'Makeup', ''),
	(15, 202, 2, 'Eyes', 'Makeup', ''),
	(16, 203, 2, 'Lips', 'Makeup', ''),
	(17, 0, 201, 'Blush', 'Face', '/skindeep/browse/blush/'),
	(18, 0, 201, 'Bronzer / Highlighter', 'Face', '/skindeep/browse/bronzer+highlighter/'),
	(19, 0, 201, 'Concealer', 'Face', '/skindeep/browse/concealer/'),
	(20, 0, 201, 'Facial Powder', 'Face', '/skindeep/browse/facial+powder/'),
	(21, 0, 201, 'Foundation', 'Face', '/skindeep/browse/foundation/'),
	(22, 0, 201, 'Makeup Remover', 'Face', '/skindeep/browse/makeup+remover/'),
	(23, 0, 201, 'Sunscreen: makeup', 'Face', '/skindeep/browse/sunscreen:+makeup/'),
	(24, 0, 202, 'Brow Liner', 'Eyes', '/skindeep/browse/brow+liner/'),
	(25, 0, 202, 'Eye Liner', 'Eyes', '/skindeep/browse/eye+liner/'),
	(26, 0, 202, 'Eye Makeup Remover', 'Eyes', '/skindeep/browse/eye+makeup+remover/'),
	(27, 0, 202, 'Eye Shadow', 'Eyes', '/skindeep/browse/eye+shadow/'),
	(28, 0, 202, 'Mascara', 'Eyes', '/skindeep/browse/mascara/'),
	(29, 0, 202, 'Eyelash glue', 'Eyes', '/skindeep/browse/eyelash+glue/'),
	(30, 0, 202, 'Other Eye Makeup', 'Eyes', '/skindeep/browse/other+eye+makeup/'),
	(31, 0, 203, 'Lip Balm', 'Lips', '/skindeep/browse/lip+balm/'),
	(32, 0, 203, 'Lip Gloss', 'Lips', '/skindeep/browse/lip+gloss/'),
	(33, 0, 203, 'Lip Liner', 'Lips', '/skindeep/browse/lip+liner/'),
	(34, 0, 203, 'Lip Plumper', 'Lips', '/skindeep/browse/lip+plumper/'),
	(35, 0, 203, 'Lipstick', 'Lips', '/skindeep/browse/lipstick/'),
	(36, 0, 203, 'Sunscreen: Lip Balm', 'Lips', '/skindeep/browse/sunscreen:+lip+balm/'),
	(37, 0, 204, 'Body Art', 'Other', '/skindeep/browse/body+art/'),
	(38, 0, 204, 'Glitter', 'Other', '/skindeep/browse/glitter/'),
	(39, 3, 0, 'Skin Care', '', ''),
	(40, 301, 3, 'Cleansing', 'Skin Care', ''),
	(41, 302, 3, 'Treating', 'Skin Care', ''),
	(42, 303, 3, 'Nourishing', 'Skin Care', ''),
	(43, 304, 3, 'Personal Care', 'Skin Care', ''),
	(44, 0, 301, 'Bar soap', 'Cleansing', '/skindeep/browse/bar+soap/'),
	(45, 0, 301, 'Bath oil / salts / soak', 'Cleansing', '/skindeep/browse/bath+oil;;salts;;soak'),
	(46, 0, 301, 'Body wash / cleanser', 'Cleansing', '/skindeep/browse/body+wash;;cleanser/'),
	(47, 0, 301, 'Bubble bath', 'Cleansing', '/skindeep/browse/bubble+bath/'),
	(48, 0, 301, 'Exfoliant/scrub', 'Cleansing', '/skindeep/browse/exfoliant;;scrub/'),
	(49, 0, 301, 'Facial cleanser', 'Cleansing', '/skindeep/browse/facial+cleanser/'),
	(50, 0, 301, 'Foot cleansing', 'Cleansing', '/skindeep/browse/foot+cleansing/'),
	(51, 0, 301, 'Hand sanitizer', 'Cleansing', '/skindeep/browse/hand+sanitizer/'),
	(52, 0, 301, 'Liquid hand soap', 'Cleansing', '/skindeep/browse/liquid+hand+soap/'),
	(53, 0, 301, 'Makeup remover', 'Cleansing', '/skindeep/browse/makeup+remover/'),
	(54, 0, 301, 'Mask', 'Cleansing', '/skindeep/browse/mask/'),
	(55, 0, 301, 'Pore strips', 'Cleansing', '/skindeep/browse/pore+strips/'),
	(56, 0, 301, 'Toners / astringents', 'Cleansing', '/skindeep/browse/toners+astringents/'),
	(60, 0, 302, 'Acne treatment', 'Treating', '/skindeep/browse/acne+treatment/'),
	(61, 0, 302, 'Anti-fungal treatment', 'Treating', '/skindeep/browse/anti-fungal+treatment/'),
	(62, 0, 302, 'Anti-itch / rash cream', 'Treating', '/skindeep/browse/anti-itch;;rash+cream/'),
	(63, 0, 302, 'Athlete\'s foot treatment', 'Treating', '/skindeep/browse/athlete\'s+foot+treatment/'),
	(64, 0, 302, 'Corn / callus treatment', 'Treating', '/skindeep/browse/corn;;callus+treatment/'),
	(65, 0, 302, 'Eczema / damaged skin treatment', 'Treating', '/skindeep/browse/eczema;;damaged+skin+treatment/'),
	(66, 0, 302, 'Foot odor control', 'Treating', '/skindeep/browse/foot+odor+control/'),
	(67, 0, 302, 'Muscle / joint soreness', 'Treating', '/skindeep/browse/muscle;;joint+soreness/'),
	(68, 0, 302, 'Oil controller', 'Treating', '/skindeep/browse/oil+controller/'),
	(69, 0, 302, 'Pain relief', 'Treating', '/skindeep/browse/pain+relief/'),
	(70, 0, 302, 'Redness / Rosacea treatment', 'Treating', '/skindeep/browse/redness;;rosacea+treatment/'),
	(71, 0, 302, 'Scar treatment', 'Treating', '/skindeep/browse/scar+treatment/'),
	(72, 0, 302, 'Skin fading / lightener', 'Treating', '/skindeep/browse/skin+fading;;lightener/'),
	(73, 0, 302, 'Varicose / spider vein treatment', 'Treating', '/skindeep/browse/varicose;;spider+vein+treatment/'),
	(74, 0, 302, 'Wound treatment', 'Treating', '/skindeep/browse/wound+treatment/'),
	(75, 0, 303, 'After sun product', 'Nourishing', '/skindeep/browse/after+sun+product/'),
	(76, 0, 303, 'Anti-aging', 'Nourishing', '/skindeep/browse/anti-aging/'),
	(77, 0, 303, 'Around-eye cream', 'Nourishing', '/skindeep/browse/around-eye+cream/'),
	(78, 0, 303, 'Body firming lotion', 'Nourishing', '/skindeep/browse/body+firming+lotion/'),
	(79, 0, 303, 'Body oil', 'Nourishing', '/skindeep/browse/body+oil/'),
	(80, 0, 303, 'Facial moisturizer / treatment', 'Nourishing', '/skindeep/browse/facial+moisturizer;;treatment/'),
	(81, 0, 303, 'Foot moisturizer', 'Nourishing', '/skindeep/browse/foot+moisturizer/'),
	(82, 0, 303, 'Hand cream', 'Nourishing', '/skindeep/browse/hand+cream/'),
	(83, 0, 303, 'Moisturizer', 'Nourishing', '/skindeep/browse/moisturizer/'),
	(84, 0, 304, 'Antiperspirant / deodorant', 'Personal Care', '/skindeep/browse/antiperspirant;;deodorant/'),
	(85, 0, 304, 'Personal cleansing', 'Personal Care', '/skindeep/browse/personal+cleansing/'),
	(86, 4, 0, 'Hair', '', ''),
	(87, 401, 4, 'Cleansing', 'Hair', ''),
	(88, 402, 4, 'Styling', 'Hair', ''),
	(89, 403, 4, 'Removal', 'Hair', ''),
	(90, 404, 4, 'Treating', 'Hair', ''),
	(91, 0, 401, 'Baby shampoo', 'Cleansing', '/skindeep/browse/baby+shampoo/'),
	(92, 0, 401, 'Conditioner', 'Cleansing', '/skindeep/browse/conditioner/'),
	(93, 0, 401, 'Shampoo', 'Cleansing', '/skindeep/browse/shampoo/'),
	(94, 0, 402, 'Detangler', 'Styling', '/skindeep/browse/detangler/'),
	(95, 0, 402, 'Hair color and bleaching', 'Styling', '/skindeep/browse/hair+color+and+bleaching/'),
	(96, 0, 402, 'Hair relaxer', 'Styling', '/skindeep/browse/hair+relaxer/'),
	(97, 0, 402, 'Hair spray', 'Styling', '/skindeep/browse/hair+spray/'),
	(98, 0, 402, 'Styling gel / lotion', 'Styling', '/skindeep/browse/styling+gel;;lotion/'),
	(99, 0, 402, 'Styling mousse / foam', 'Styling', '/skindeep/browse/styling+mousse;;foam/'),
	(100, 0, 403, 'Depilatory', 'Removal', '/skindeep/browse/depilatory/'),
	(101, 0, 403, 'Hair removal waxes', 'Removal', '/skindeep/browse/hair+removal+waxes/'),
	(102, 0, 404, 'Dandruff / scalp treatment', 'Treating', '/skindeep/browse/dandruff;;scalp+treatment/'),
	(103, 0, 404, 'hair-loss treatment', 'Treating', '/skindeep/browse/hair-loss+treatment/'),
	(104, 5, 0, 'Nails', '', ''),
	(105, 502, 5, 'Treatment', 'Nails', ''),
	(106, 501, 5, 'Styling', 'Nails', ''),
	(107, 0, 501, 'Nail glue', 'Styling', '/skindeep/browse/nail+glue/'),
	(108, 0, 501, 'Nail polish', 'Styling', '/skindeep/browse/nail+polish/'),
	(109, 0, 501, 'Polish remover', 'Styling', '/skindeep/browse/polish+remover/'),
	(110, 0, 502, 'Cuticle treatment', 'Treatment', '/skindeep/browse/cuticle+treatment/'),
	(111, 0, 502, 'Nail treatment', 'Treatment', '/skindeep/browse/nail+treatment/'),
	(112, 0, 502, 'Polish remover', 'Treatment', '/skindeep/browse/polish+remover/'),
	(113, 6, 0, 'Fragrance', '', ''),
	(114, 0, 6, 'Body spray', 'Fragrance', '/skindeep/browse/body+spray/'),
	(115, 0, 6, 'Fragrance for men', 'Fragrance', '/skindeep/browse/fragrance+for+men/'),
	(116, 0, 6, 'Fragrance for women', 'Fragrance', '/skindeep/browse/fragrance+for+women/'),
	(117, 7, 0, 'Babies &amp; Moms', '', ''),
	(118, 0, 7, 'Baby bubble bath', 'Babies &amp; Moms', '/skindeep/browse/baby+bubble+bath/'),
	(119, 0, 7, 'Baby lotion', 'Babies &amp; Moms', '/skindeep/browse/baby+lotion/'),
	(120, 0, 7, 'Baby oil', 'Babies &amp; Moms', '/skindeep/browse/baby+oil/'),
	(121, 0, 7, 'Baby powder', 'Babies &amp; Moms', '/skindeep/browse/baby+powder/'),
	(122, 0, 7, 'Baby shampoo', 'Babies &amp; Moms', '/skindeep/browse/baby+shampoo/'),
	(123, 0, 7, 'Baby soap', 'Babies &amp; Moms', '/skindeep/browse/baby+soap/'),
	(124, 0, 7, 'Baby toothpaste', 'Babies &amp; Moms', '/skindeep/browse/baby+toothpaste/'),
	(125, 0, 7, 'Baby wipes', 'Babies &amp; Moms', '/skindeep/browse/baby+wipes/'),
	(126, 0, 7, 'Cradle cap treatment', 'Babies &amp; Moms', '/skindeep/browse/cradle+cap+treatment/'),
	(127, 0, 7, 'Diaper cream', 'Babies &amp; Moms', '/skindeep/browse/diaper+cream/'),
	(128, 8, 0, 'Oral Care', '', ''),
	(129, 0, 8, 'Baby toothpaste', 'Oral Care', '/skindeep/browse/baby+toothpaste/'),
	(130, 0, 8, 'Breath fresheners', 'Oral Care', '/skindeep/browse/breath+fresheners/'),
	(131, 0, 8, 'Lip balm', 'Oral Care', '/skindeep/browse/lip+balm/'),
	(132, 0, 8, 'Mouthwash', 'Oral Care', '/skindeep/browse/mouthwash/'),
	(133, 0, 8, 'Tooth whitening', 'Oral Care', '/skindeep/browse/tooth+whitening/'),
	(134, 0, 8, 'Toothpaste', 'Oral Care', '/skindeep/browse/toothpaste/'),
	(135, 9, 0, 'Men\'s', '', ''),
	(136, 901, 9, 'Face', 'Men\'s', ''),
	(137, 902, 9, 'Body', 'Men\'s', ''),
	(138, 903, 9, 'Hair', 'Men\'s', ''),
	(139, 0, 901, 'After shave', 'Face', '/skindeep/browse/after+shave/'),
	(140, 0, 901, 'Facial clea', 'Face', '/skindeep/browse/facial+cleanser/'),
	(141, 0, 901, 'Facial moisturizer / treatment', 'Face', '/skindeep/browse/facial+moisturizer;;treatment/'),
	(142, 0, 901, 'Shaving cream ', 'Face', '/skindeep/browse/shaving+cream/'),
	(143, 0, 903, 'Hair color and bleaching', 'Hair', '/skindeep/browse/hair+color+and+bleaching/'),
	(144, 0, 903, 'Hair-loss treatment', 'Hair', '/skindeep/browse/hair-loss+treatment/'),
	(145, 0, 903, 'Shampoo', 'Hair', '/skindeep/browse/shampoo/'),
	(146, 0, 903, 'Styling gel / lotion', 'Hair', '/skindeep/browse/styling+gel;;lotion/'),
	(147, 0, 902, 'Antiperspirant / deodorant', 'Body', '/skindeep/browse/antiperspirant;;deodorant/'),
	(148, 0, 902, 'Body spray', 'Body', '/skindeep/browse/body+spray/'),
	(149, 0, 902, 'Body wash / cleanser', 'Body', '/skindeep/browse/body+wash;;cleanser/'),
	(150, 0, 902, 'Fragrance for men', 'Body', '/skindeep/browse/fragrance+for+men/');

